/**
 * Jail Commander profiles — one per PNGCS correctional institution nationwide.
 * Matches js/institutions-data.js (19 facilities). Password for all demo accounts: Password123!
 */
const PNGCS_JAIL_COMMANDERS = [
  { instIndex: 1, institutionName: 'Bomana Correctional Institution', province: 'National Capital District', firstName: 'James', lastName: 'Wari', employeeNumber: 'EMP-10001', phone: '+675 7345 6789', username: 'commander@cs.gov.pg', dateAppointed: '2019-03-15' },
  { instIndex: 2, institutionName: 'Buimo Correctional Service Facility', province: 'Morobe', firstName: 'Michael', lastName: 'Turi', employeeNumber: 'EMP-10002', phone: '+675 472 1101', username: 'm.turi@cs.gov.pg', dateAppointed: '2020-06-01' },
  { instIndex: 3, institutionName: 'Baisu Correctional Service Facility', province: 'Western Highlands', firstName: 'Peter', lastName: 'Koma', employeeNumber: 'EMP-10003', phone: '+675 542 2202', username: 'p.koma@cs.gov.pg', dateAppointed: '2018-11-20' },
  { instIndex: 4, institutionName: 'Kerevat Correctional Service Facility', province: 'East New Britain', firstName: 'Robert', lastName: 'Namaliu', employeeNumber: 'EMP-10004', phone: '+675 982 3303', username: 'r.namaliu@cs.gov.pg', dateAppointed: '2021-02-10' },
  { instIndex: 5, institutionName: 'Boram Jail', province: 'East Sepik', firstName: 'David', lastName: 'Amini', employeeNumber: 'EMP-10005', phone: '+675 856 4404', username: 'd.amini@cs.gov.pg', dateAppointed: '2017-08-05' },
  { instIndex: 6, institutionName: 'Bihute Correctional Service Facility', province: 'Eastern Highlands', firstName: 'Simon', lastName: 'Gideon', employeeNumber: 'EMP-10006', phone: '+675 531 5505', username: 's.gideon@cs.gov.pg', dateAppointed: '2019-09-12' },
  { instIndex: 7, institutionName: 'Barawagi Correctional Service Facility', province: 'Chimbu', firstName: 'Thomas', lastName: 'Kuri', employeeNumber: 'EMP-10007', phone: '+675 545 6606', username: 't.kuri@cs.gov.pg', dateAppointed: '2020-01-22' },
  { instIndex: 8, institutionName: 'Bundaira Correctional Service Facility', province: 'Eastern Highlands', firstName: 'William', lastName: 'Aua', employeeNumber: 'EMP-10008', phone: '+675 532 7707', username: 'w.aua@cs.gov.pg', dateAppointed: '2018-04-18' },
  { instIndex: 9, institutionName: 'Bui-Iebi Correctional Service Facility', province: 'Southern Highlands', firstName: 'Joseph', lastName: 'Mond', employeeNumber: 'EMP-10009', phone: '+675 549 8808', username: 'j.mond@cs.gov.pg', dateAppointed: '2021-07-30' },
  { instIndex: 10, institutionName: 'Kavieng Correctional Service Facility', province: 'New Ireland', firstName: 'Andrew', lastName: 'Sakias', employeeNumber: 'EMP-10010', phone: '+675 984 9909', username: 'a.sakias@cs.gov.pg', dateAppointed: '2019-12-01' },
  { instIndex: 11, institutionName: 'Manus Correctional Service Facility', province: 'Manus', firstName: 'George', lastName: 'Manu', employeeNumber: 'EMP-10011', phone: '+675 970 1010', username: 'g.manu@cs.gov.pg', dateAppointed: '2020-03-08' },
  { instIndex: 12, institutionName: 'Lakiemata Correctional Service Facility', province: 'West New Britain', firstName: 'Henry', lastName: 'Pokas', employeeNumber: 'EMP-10012', phone: '+675 983 1111', username: 'h.pokas@cs.gov.pg', dateAppointed: '2018-10-14' },
  { instIndex: 13, institutionName: 'Daru Correctional Service Facility', province: 'Western', firstName: 'Daniel', lastName: 'Dibod', employeeNumber: 'EMP-10013', phone: '+675 645 1212', username: 'd.dibod@cs.gov.pg', dateAppointed: '2021-05-25' },
  { instIndex: 14, institutionName: 'Giligili Correctional Service Facility', province: 'Milne Bay', firstName: 'Paul', lastName: 'Vege', employeeNumber: 'EMP-10014', phone: '+675 641 1313', username: 'p.vege@cs.gov.pg', dateAppointed: '2019-06-19' },
  { instIndex: 15, institutionName: 'Beon Correctional Service Facility', province: 'Madang', firstName: 'Francis', lastName: 'Yambut', employeeNumber: 'EMP-10015', phone: '+675 422 1414', username: 'f.yambut@cs.gov.pg', dateAppointed: '2020-11-03' },
  { instIndex: 16, institutionName: 'Vanimo Correctional Service Facility', province: 'West Sepik', firstName: 'Steven', lastName: 'Aitape', employeeNumber: 'EMP-10016', phone: '+675 857 1515', username: 's.aitape@cs.gov.pg', dateAppointed: '2018-02-28' },
  { instIndex: 17, institutionName: 'Biru Correctional Service Facility', province: 'Northern', firstName: 'Mark', lastName: 'Ovia', employeeNumber: 'EMP-10017', phone: '+675 323 1616', username: 'm.ovia@cs.gov.pg', dateAppointed: '2021-09-07' },
  { instIndex: 18, institutionName: 'Mukurumanda Correctional Service Facility', province: 'Enga', firstName: 'Chris', lastName: 'Kipoi', employeeNumber: 'EMP-10018', phone: '+675 547 1717', username: 'c.kipoi@cs.gov.pg', dateAppointed: '2019-04-11' },
  { instIndex: 19, institutionName: 'Hawa Correctional Service Facility', province: 'Hela', firstName: 'Benjamin', lastName: 'Hagu', employeeNumber: 'EMP-10019', phone: '+675 548 1818', username: 'b.hagu@cs.gov.pg', dateAppointed: '2020-08-16' },
];
